//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBZZWebservices
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HBZZWebservices.HBZZWebservicesSoap")]
    public interface HBZZWebservicesSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<HBZZWebservices.HelloWorldResponse> HelloWorldAsync(HBZZWebservices.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetDataToServer", ReplyAction="*")]
        System.Threading.Tasks.Task<HBZZWebservices.SetDataToServerResponse> SetDataToServerAsync(HBZZWebservices.SetDataToServerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetDataToServerPicture", ReplyAction="*")]
        System.Threading.Tasks.Task<HBZZWebservices.SetDataToServerPictureResponse> SetDataToServerPictureAsync(HBZZWebservices.SetDataToServerPictureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostDataToServer", ReplyAction="*")]
        System.Threading.Tasks.Task<HBZZWebservices.PostDataToServerResponse> PostDataToServerAsync(HBZZWebservices.PostDataToServerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFileEx", ReplyAction="*")]
        System.Threading.Tasks.Task<HBZZWebservices.UploadFileExResponse> UploadFileExAsync(HBZZWebservices.UploadFileExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Post", ReplyAction="*")]
        System.Threading.Tasks.Task<HBZZWebservices.PostResponse> PostAsync(HBZZWebservices.PostRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public HBZZWebservices.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(HBZZWebservices.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public HBZZWebservices.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(HBZZWebservices.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataToServerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDataToServer", Namespace="http://tempuri.org/", Order=0)]
        public HBZZWebservices.SetDataToServerRequestBody Body;
        
        public SetDataToServerRequest()
        {
        }
        
        public SetDataToServerRequest(HBZZWebservices.SetDataToServerRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDataToServerRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string jkid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jyjgbm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sqm;
        
        public SetDataToServerRequestBody()
        {
        }
        
        public SetDataToServerRequestBody(string url, string jkid, string sendData, string jyjgbm, string sqm)
        {
            this.url = url;
            this.jkid = jkid;
            this.sendData = sendData;
            this.jyjgbm = jyjgbm;
            this.sqm = sqm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataToServerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDataToServerResponse", Namespace="http://tempuri.org/", Order=0)]
        public HBZZWebservices.SetDataToServerResponseBody Body;
        
        public SetDataToServerResponse()
        {
        }
        
        public SetDataToServerResponse(HBZZWebservices.SetDataToServerResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDataToServerResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetDataToServerResult;
        
        public SetDataToServerResponseBody()
        {
        }
        
        public SetDataToServerResponseBody(string SetDataToServerResult)
        {
            this.SetDataToServerResult = SetDataToServerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataToServerPictureRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDataToServerPicture", Namespace="http://tempuri.org/", Order=0)]
        public HBZZWebservices.SetDataToServerPictureRequestBody Body;
        
        public SetDataToServerPictureRequest()
        {
        }
        
        public SetDataToServerPictureRequest(HBZZWebservices.SetDataToServerPictureRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDataToServerPictureRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string jkid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jyjgbm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sqm;
        
        public SetDataToServerPictureRequestBody()
        {
        }
        
        public SetDataToServerPictureRequestBody(string url, string jkid, string sendData, string jyjgbm, string sqm)
        {
            this.url = url;
            this.jkid = jkid;
            this.sendData = sendData;
            this.jyjgbm = jyjgbm;
            this.sqm = sqm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataToServerPictureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDataToServerPictureResponse", Namespace="http://tempuri.org/", Order=0)]
        public HBZZWebservices.SetDataToServerPictureResponseBody Body;
        
        public SetDataToServerPictureResponse()
        {
        }
        
        public SetDataToServerPictureResponse(HBZZWebservices.SetDataToServerPictureResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDataToServerPictureResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] SetDataToServerPictureResult;
        
        public SetDataToServerPictureResponseBody()
        {
        }
        
        public SetDataToServerPictureResponseBody(byte[] SetDataToServerPictureResult)
        {
            this.SetDataToServerPictureResult = SetDataToServerPictureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostDataToServerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostDataToServer", Namespace="http://tempuri.org/", Order=0)]
        public HBZZWebservices.PostDataToServerRequestBody Body;
        
        public PostDataToServerRequest()
        {
        }
        
        public PostDataToServerRequest(HBZZWebservices.PostDataToServerRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostDataToServerRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string poststring;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string url;
        
        public PostDataToServerRequestBody()
        {
        }
        
        public PostDataToServerRequestBody(string poststring, string url)
        {
            this.poststring = poststring;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostDataToServerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostDataToServerResponse", Namespace="http://tempuri.org/", Order=0)]
        public HBZZWebservices.PostDataToServerResponseBody Body;
        
        public PostDataToServerResponse()
        {
        }
        
        public PostDataToServerResponse(HBZZWebservices.PostDataToServerResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostDataToServerResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostDataToServerResult;
        
        public PostDataToServerResponseBody()
        {
        }
        
        public PostDataToServerResponseBody(string PostDataToServerResult)
        {
            this.PostDataToServerResult = PostDataToServerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileExRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileEx", Namespace="http://tempuri.org/", Order=0)]
        public HBZZWebservices.UploadFileExRequestBody Body;
        
        public UploadFileExRequest()
        {
        }
        
        public UploadFileExRequest(HBZZWebservices.UploadFileExRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileExRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jkId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string jkYhm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string jkSqm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string crcCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SendJson;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string url;
        
        public UploadFileExRequestBody()
        {
        }
        
        public UploadFileExRequestBody(string jkId, string jkYhm, string jkSqm, string crcCode, string SendJson, string url)
        {
            this.jkId = jkId;
            this.jkYhm = jkYhm;
            this.jkSqm = jkSqm;
            this.crcCode = crcCode;
            this.SendJson = SendJson;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileExResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileExResponse", Namespace="http://tempuri.org/", Order=0)]
        public HBZZWebservices.UploadFileExResponseBody Body;
        
        public UploadFileExResponse()
        {
        }
        
        public UploadFileExResponse(HBZZWebservices.UploadFileExResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileExResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadFileExResult;
        
        public UploadFileExResponseBody()
        {
        }
        
        public UploadFileExResponseBody(string UploadFileExResult)
        {
            this.UploadFileExResult = UploadFileExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Post", Namespace="http://tempuri.org/", Order=0)]
        public HBZZWebservices.PostRequestBody Body;
        
        public PostRequest()
        {
        }
        
        public PostRequest(HBZZWebservices.PostRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        public PostRequestBody()
        {
        }
        
        public PostRequestBody(string url, string content)
        {
            this.url = url;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostResponse", Namespace="http://tempuri.org/", Order=0)]
        public HBZZWebservices.PostResponseBody Body;
        
        public PostResponse()
        {
        }
        
        public PostResponse(HBZZWebservices.PostResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostResult;
        
        public PostResponseBody()
        {
        }
        
        public PostResponseBody(string PostResult)
        {
            this.PostResult = PostResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface HBZZWebservicesSoapChannel : HBZZWebservices.HBZZWebservicesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class HBZZWebservicesSoapClient : System.ServiceModel.ClientBase<HBZZWebservices.HBZZWebservicesSoap>, HBZZWebservices.HBZZWebservicesSoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HBZZWebservicesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(HBZZWebservicesSoapClient.GetBindingForEndpoint(endpointConfiguration), HBZZWebservicesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HBZZWebservicesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HBZZWebservicesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HBZZWebservicesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HBZZWebservicesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HBZZWebservicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HBZZWebservices.HelloWorldResponse> HBZZWebservices.HBZZWebservicesSoap.HelloWorldAsync(HBZZWebservices.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<HBZZWebservices.HelloWorldResponse> HelloWorldAsync()
        {
            HBZZWebservices.HelloWorldRequest inValue = new HBZZWebservices.HelloWorldRequest();
            inValue.Body = new HBZZWebservices.HelloWorldRequestBody();
            return ((HBZZWebservices.HBZZWebservicesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HBZZWebservices.SetDataToServerResponse> HBZZWebservices.HBZZWebservicesSoap.SetDataToServerAsync(HBZZWebservices.SetDataToServerRequest request)
        {
            return base.Channel.SetDataToServerAsync(request);
        }
        
        public System.Threading.Tasks.Task<HBZZWebservices.SetDataToServerResponse> SetDataToServerAsync(string url, string jkid, string sendData, string jyjgbm, string sqm)
        {
            HBZZWebservices.SetDataToServerRequest inValue = new HBZZWebservices.SetDataToServerRequest();
            inValue.Body = new HBZZWebservices.SetDataToServerRequestBody();
            inValue.Body.url = url;
            inValue.Body.jkid = jkid;
            inValue.Body.sendData = sendData;
            inValue.Body.jyjgbm = jyjgbm;
            inValue.Body.sqm = sqm;
            return ((HBZZWebservices.HBZZWebservicesSoap)(this)).SetDataToServerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HBZZWebservices.SetDataToServerPictureResponse> HBZZWebservices.HBZZWebservicesSoap.SetDataToServerPictureAsync(HBZZWebservices.SetDataToServerPictureRequest request)
        {
            return base.Channel.SetDataToServerPictureAsync(request);
        }
        
        public System.Threading.Tasks.Task<HBZZWebservices.SetDataToServerPictureResponse> SetDataToServerPictureAsync(string url, string jkid, string sendData, string jyjgbm, string sqm)
        {
            HBZZWebservices.SetDataToServerPictureRequest inValue = new HBZZWebservices.SetDataToServerPictureRequest();
            inValue.Body = new HBZZWebservices.SetDataToServerPictureRequestBody();
            inValue.Body.url = url;
            inValue.Body.jkid = jkid;
            inValue.Body.sendData = sendData;
            inValue.Body.jyjgbm = jyjgbm;
            inValue.Body.sqm = sqm;
            return ((HBZZWebservices.HBZZWebservicesSoap)(this)).SetDataToServerPictureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HBZZWebservices.PostDataToServerResponse> HBZZWebservices.HBZZWebservicesSoap.PostDataToServerAsync(HBZZWebservices.PostDataToServerRequest request)
        {
            return base.Channel.PostDataToServerAsync(request);
        }
        
        public System.Threading.Tasks.Task<HBZZWebservices.PostDataToServerResponse> PostDataToServerAsync(string poststring, string url)
        {
            HBZZWebservices.PostDataToServerRequest inValue = new HBZZWebservices.PostDataToServerRequest();
            inValue.Body = new HBZZWebservices.PostDataToServerRequestBody();
            inValue.Body.poststring = poststring;
            inValue.Body.url = url;
            return ((HBZZWebservices.HBZZWebservicesSoap)(this)).PostDataToServerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HBZZWebservices.UploadFileExResponse> HBZZWebservices.HBZZWebservicesSoap.UploadFileExAsync(HBZZWebservices.UploadFileExRequest request)
        {
            return base.Channel.UploadFileExAsync(request);
        }
        
        public System.Threading.Tasks.Task<HBZZWebservices.UploadFileExResponse> UploadFileExAsync(string jkId, string jkYhm, string jkSqm, string crcCode, string SendJson, string url)
        {
            HBZZWebservices.UploadFileExRequest inValue = new HBZZWebservices.UploadFileExRequest();
            inValue.Body = new HBZZWebservices.UploadFileExRequestBody();
            inValue.Body.jkId = jkId;
            inValue.Body.jkYhm = jkYhm;
            inValue.Body.jkSqm = jkSqm;
            inValue.Body.crcCode = crcCode;
            inValue.Body.SendJson = SendJson;
            inValue.Body.url = url;
            return ((HBZZWebservices.HBZZWebservicesSoap)(this)).UploadFileExAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HBZZWebservices.PostResponse> HBZZWebservices.HBZZWebservicesSoap.PostAsync(HBZZWebservices.PostRequest request)
        {
            return base.Channel.PostAsync(request);
        }
        
        public System.Threading.Tasks.Task<HBZZWebservices.PostResponse> PostAsync(string url, string content)
        {
            HBZZWebservices.PostRequest inValue = new HBZZWebservices.PostRequest();
            inValue.Body = new HBZZWebservices.PostRequestBody();
            inValue.Body.url = url;
            inValue.Body.content = content;
            return ((HBZZWebservices.HBZZWebservicesSoap)(this)).PostAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HBZZWebservicesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HBZZWebservicesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HBZZWebservicesSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8082/HBZZWebservices.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.HBZZWebservicesSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8082/HBZZWebservices.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HBZZWebservicesSoap,
            
            HBZZWebservicesSoap12,
        }
    }
}
